name: Schedule Supabase Function
on:
  schedule:
    - cron: "0 1 * * *"  # runs the script to update the DB contents @ 8pm EST (daily)

jobs:
  call_function:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          curl -X POST "$VITE_SUPABASE_URL/functions/v1/updateMembers" \
               -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY"
